In [ ]:
from sklearn.datasets import load_iris

from NaiveBayes import GaussianNaiveBayes
import numpy as np
import sys
import os
sys.path.append(os.path.abspath(os.path.join('..', 'Preprocessing')))
from Preprocessing import Train_And_Test

data = load_iris()
X = np.array(data.data)
y = np.array(data.target)
    
X_train, X_test, y_train, y_test = Train_And_Test(X, y, 0.8)

model = GaussianNaiveBayes()

model.fit(X_train, y_train)


model.score(X_test, y_test)


[[ 1.  2.  3.  1.  2.  3.  4.  6.  9.]
 [ 4.  5.  6. 16. 20. 24. 25. 30. 36.]
 [ 7.  8.  9. 49. 56. 63. 64. 72. 81.]]


{'Accuracy': 1.0, 'Recall': 1.0, 'Precision': 1.0, 'F1 Score': 1.0}